[pytest]

pythonpath = .

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    unit: test unitaires rapides pour valider l'algorithme d'une fonction sans navigateur
    integration : test de deploiement des pages
    e2e: test du parcours de l'utilisateur necessitant un navigateur (selenium)